services:
  web:
    working_dir: /code
    build: ./
    command: ./entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=django_db_dev
      - POSTGRES_HOST=db
    depends_on:
      - db
      - redis
    networks:
      - main
  db:
    image: postgis/postgis:15-3.5
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=django_db_dev
      - POSTGRES_HOST=db
    networks:
      - main
  redis:
    image: redis:latest
    restart: always
    networks:
      - main
volumes:
  postgres_data:
networks:
  main:
    external: true
