services:
  web:
    working_dir: /code
    build: ./
    command: ./entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=django_db_dev
      - POSTGRES_HOST=db
      - REDIS_URL=redis://redis:6379/
    depends_on:
      - db
      - redis
  db:
    image: postgis/postgis:15-3.5
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=django_db_dev
      - POSTGRES_HOST=db
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
volumes:
  postgres_data:
