# Generated by Django 5.2.3 on 2025-06-11 12:57

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gduser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='gduser',
            name='account_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Private'), (2, 'Developer Admin'), (3, 'Developer Employee'), (4, 'State official')], default=1),
        ),
        migrations.AddField(
            model_name='gduser',
            name='allow_email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gduser',
            name='allow_push_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gduser',
            name='allow_sms_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gduser',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='gduser',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gduser',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo'),
        ),
        migrations.AddField(
            model_name='gduser',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='gduser',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gduser',
            name='country',
            field=django_countries.fields.CountryField(default='PL', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gduser',
            name='house_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='gduser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='gduser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo'),
        ),
        migrations.AddField(
            model_name='gduser',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='gduser',
            name='street',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='gduser',
            name='zip_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
