# Generated by Django 5.2.3 on 2025-06-11 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_gduser_managers_gduser_account_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gduser',
            old_name='allow_push_notifications',
            new_name='subscribe_to_newsletter',
        ),
    ]
