# Generated by Django 5.2.3 on 2025-06-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_allow_push_notifications_gduser_subscribe_to_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gduser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
    ]
