# Generated by Django 5.2.3 on 2025-06-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_gduser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gduser',
            name='account_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Private'), (2, 'Triage Admin'), (3, 'Developer Admin'), (4, 'Developer Employee'), (5, 'State official')], default=1),
        ),
    ]
