# Generated by Django 5.1.4 on 2024-12-12 11:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="OSMPoint",
            fields=[
                ("osm_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("leisure", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=120)),
                ("way", django.contrib.gis.db.models.fields.PointField(geography=True, srid=3857)),
                ("shop", models.CharField(max_length=120)),
                ("religion", models.CharField(max_length=120)),
            ],
            options={
                "db_table": "ostgres_point",
                "managed": False,
            },
        ),
    ]
