# Generated by Django 5.2.3 on 2025-06-11 10:33

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Apartment'), (2, 'Garage'), (3, 'House'), (4, 'Room'), (5, 'Plot')], default=1)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Loft'), (2, 'Single'), (3, 'Shared')], default=2)),
                ('title', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('square_meters', models.PositiveIntegerField()),
                ('rooms', models.PositiveIntegerField()),
                ('construction_year', models.PositiveIntegerField(null=True)),
                ('addrline1', models.CharField(max_length=250)),
                ('addrline2', models.CharField(blank=True, max_length=250)),
                ('deposit', models.PositiveIntegerField(blank=True, null=True)),
                ('deposit_received', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('air_conditioning', models.BooleanField(null=True)),
                ('broadband', models.BooleanField(null=True)),
                ('available_in', models.SmallIntegerField(blank=True)),
                ('floor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Floor')),
                ('floors', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of floors')),
                ('energy_certificate', models.CharField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('lease_terms', models.PositiveIntegerField(blank=True, null=True)),
                ('lift', models.BooleanField(null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField()),
                ('file', models.ImageField(blank=True, upload_to='photos')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='offer.offer')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
