# Generated by Django 5.1.4 on 2024-12-13 01:00

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appliances",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Appliance",
                "verbose_name_plural": "Appliances",
            },
        ),
        migrations.CreateModel(
            name="Flooring",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                "verbose_name": "Flooring",
                "verbose_name_plural": "Flooring",
            },
        ),
        migrations.CreateModel(
            name="HeatingType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Heating Type",
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("file", models.ImageField(blank=True, upload_to="photos")),
            ],
            options={
                "verbose_name": "Photo",
                "verbose_name_plural": "Photos",
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rent", models.PositiveIntegerField(blank=True)),
                ("square_meters", models.PositiveIntegerField()),
                ("price", models.PositiveIntegerField(blank=True)),
                ("deposit", models.PositiveIntegerField()),
                ("construction_year", models.PositiveIntegerField(null=True)),
                ("title", models.CharField(max_length=200)),
                ("energy_certificate", models.CharField(blank=True, null=True)),
                ("description", models.TextField(max_length=2000)),
                ("phone_number", phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ("rooms", models.PositiveIntegerField()),
                ("lease_terms", models.PositiveIntegerField(blank=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("lift", models.BooleanField(null=True)),
                ("broadband", models.CharField(blank=True, max_length=250, null=True)),
                ("floor", models.PositiveIntegerField(blank=True, null=True)),
                ("appliances", models.ManyToManyField(blank=True, to="offer.appliances")),
                ("flooring", models.ManyToManyField(blank=True, to="offer.flooring")),
                ("heating_type", models.ManyToManyField(blank=True, to="offer.heatingtype")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("photos", models.ManyToManyField(to="offer.photo")),
            ],
            options={
                "verbose_name": "Offer",
                "verbose_name_plural": "Offers",
            },
        ),
    ]
