# Generated by Django 5.2.3 on 2025-06-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Deleted'), (4, 'Pending'), (5, 'Rejected'), (6, 'Accepted')], default=4),
        ),
        migrations.AddField(
            model_name='offer',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='virtual_tour',
            field=models.URLField(blank=True, null=True),
        ),
    ]
