# Generated by Django 5.2.3 on 2025-06-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_offer_status_offer_video_offer_virtual_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Expired'), (3, 'Pending'), (4, 'Rejected')], default=3),
        ),
    ]
