# Generated by Django 5.2.3 on 2025-06-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_offer_uuid_alter_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='slug',
            field=models.SlugField(default='blah', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
