# Generated by Django 5.2.3 on 2025-06-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PLN'), (2, 'EUR'), (3, 'USD'), (4, 'GBP')], default=1),
        ),
    ]
