# Generated by Django 5.2.3 on 2025-06-12 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_offer_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='construction_year',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
