# Generated by Django 5.2.3 on 2025-06-12 18:08

import apps.shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_alter_offer_construction_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='construction_year',
            field=models.PositiveIntegerField(null=True, validators=[apps.shared.validators.validate_current_year]),
        ),
    ]
