name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: "Set up python 3.13"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - uses: Gr1N/setup-poetry@v8
      - name: "Ssave poetry cache"
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: "Install dependencies"
        run: poetry install
      - name: "Install GDAL"
        run: sudo apt-get install binutils libproj-dev gdal-bin --no-install-suggests --no-install-recommends --yes
      - name: "Run tests"
        run: poetry run python manage.py test
