name: Use isort

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: "Fetch code"
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: "Set up python 3.13"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - name: "Install pre-commit"
        run: pip install pre-commit
      - name: "Run linters"
        run: pre-commit run -a
